server:
  port: 8001
spring:
  application:
    name: config-server-8001
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/zjhGH/cloud-client.git
          # 远程仓库的文件夹地址
          search-paths: /config-server-8001/config
          # 默认分支
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/