server:
  port: 7001
spring:
  application:
    # 指定注册到eureka server上的服务名称,对于电影微服务，此处名称设为microservice-consumer-movie
    name: client-7001
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少，要注册多个时用逗号隔开
      defaultZone: http://localhost:6001/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    instance-id: client:7001